Create `<Flag />` Component and Package, Export All Parts
selsa-inube/inubekit-flag pull request #23
Opened 2024-08-05 22:18 UTC by cmarin001

This pull request introduces the new `<Flag />` component and packages it along with its associated parts: `FlagsProvider`, `useFlag()`, `FlagsPortal`, `Flag`, and the `IFlag` interface, ensuring they are all properly exported for modularity and reusability across the application.

2024-08-06 15:04 UTC, wfercanas requested changes

2024-08-06 15:04 UTC, wfercanas commented on src/components/FlagPortal/FlagPortal.stories.tsx
> +      closeFlag: action("Flag closed"),
Closing the flag in storybook doens't work

2024-08-06 15:04 UTC, wfercanas commented on src/components/FlagPortal/styles.js
> +  top: 10px;
The flag container should be fixed related to the bottom, not the top.

2024-08-20 19:54 UTC, cmarin001 commented on src/providers/FlagsProvider.tsx
> +  const addMessage = (message: Omit<IFlag, "id">) => {
solved

2024-08-20 19:54 UTC, cmarin001 commented on src/providers/FlagsProvider.tsx
> +  const removeMessage = (id: string) => {
solved

2024-08-20 19:57 UTC, cmarin001 commented on src/components/FlagPortal/styles.js
> +  top: 10px;
solved

2024-08-20 20:29 UTC, cmarin001 commented on src/components/FlagPortal/FlagPortal.stories.tsx
> +      closeFlag: action("Flag closed"),
solved

2024-08-20 20:45 UTC, cmarin001 commented on src/components/Flag/index.tsx
> +  isMessageResponsive?: boolean;
solved

2024-08-20 21:24 UTC, cmarin001 commented on src/components/Flag/styles.js
solved

2024-08-23 15:54 UTC, wfercanas requested changes

2024-08-23 15:54 UTC, wfercanas commented on src/components/Flag/styles.js
The flag in figma has two variants, one for using in desktop screens and another one for tablets.
Use media-queries so that when the width of the screen equals the width of the flag we change the flag to the small version.

2024-08-23 15:54 UTC, wfercanas commented on src/components/Flag/styles.js
Adjust bottom and right css properties to make the flag be fixed there. Check these mockups and find a flag to determine how many pixels should be used: https://www.figma.com/design/tVCel8FnrVZYoFCISHClKG/Personal-data?node-id=2619-70767&t=u4qAzV6YvWUb2kjm-0

2024-08-23 15:54 UTC, wfercanas commented on src/components/Flag/index.tsx
> +  MdChat,
This icon should be `MdOutlineChat`

2024-08-23 15:54 UTC, wfercanas commented on src/components/FlagPortal/FlagPortal.stories.tsx
> +      closeFlag: action("Flag closed"),
Close flag is not a prop that should be exposed by the component, because that means that we're delegating that responsibility to the implementation.

1. If the user clicks the "X" at the top-right corner, the removeFlag method should be triggered and that should change the context by removing this exact flag.
2. When the time expires, the removeFlag should be triggered as well and that also deletes this exact flag from the state in context.

2024-08-23 15:54 UTC, wfercanas commented on src/components/Flag/index.tsx
Directly use "dark" as appearance for the close Icon. Delete `closeIconAppearance` variable.

2024-08-23 15:54 UTC, wfercanas commented on src/components/Flag/index.tsx
Checking how we structured the tokens, it seems kind of crazy to define the appearance of a "warning" flag ends up being "danger" for countdown bar or icon. I will delete all tokens for the flag.

1. If the user passes the appearance "danger" to the flag, we directly use that value for the icon and the countdown bar, without parsing tokens.
2. Remove the light flag. This will be changed in figma as well.
3. The title will always be dark and the description will always be gray.
4. The background will always be n0

2024-08-23 15:54 UTC, wfercanas commented on src/components/FlagPortal/index.tsx
> +      {flags.map((msg) => (
Change `msg` to `flag`

2024-08-23 15:54 UTC, wfercanas commented on src/components/FlagPortal/index.tsx
> +        />
It would be better to not have two entities (message and flag) when we can have only one: flag. 
If a flag have and know their own ids we can reduce the complexity of the state and rendering of the flag.

Example:

```js
flags.map(flag  => (
  <Flag 
    key={flag.id}
    closeFlag={() => removeFlag(flag.id)}
  />
))
```

2024-08-23 16:52 UTC, cmarin001 commented on src/components/Flag/index.tsx
> +  MdChat,
solved

2024-08-23 16:54 UTC, cmarin001 commented on src/components/Flag/index.tsx
solved

2024-08-23 16:59 UTC, cmarin001 commented on src/components/FlagPortal/index.tsx
> +        />
solved

2024-08-23 17:00 UTC, cmarin001 commented on src/components/FlagPortal/index.tsx
> +      {flags.map((msg) => (
solved

2024-08-23 17:10 UTC, cmarin001 commented on src/components/Flag/index.tsx
solved

2024-08-23 17:41 UTC, cmarin001 commented on src/components/FlagPortal/FlagPortal.stories.tsx
> +      closeFlag: action("Flag closed"),
solved

2024-08-23 20:56 UTC, cmarin001 commented on src/components/Flag/styles.js
solved

2024-08-23 21:43 UTC, cmarin001 commented on src/components/Flag/styles.js
solved

2024-08-28 15:30 UTC, wfercanas requested changes

2024-08-28 15:30 UTC, wfercanas commented on src/components/Flag/styles.js
>      0px 1px 3px 1px rgba(0, 0, 0, 0.15);
The shadow properties don't match what's in figma:

![image](https://github.com/user-attachments/assets/b1f4e6f0-a6f5-474a-a686-958b6d74c439)

2024-08-28 15:30 UTC, wfercanas commented on src/components/Flag/styles.js
>  const StyledFlag = styled.div`
1. Change StyledFlag to be a `li`
2. Add the property `list-style: none` to avoid breaking the flag.

2024-08-28 15:30 UTC, wfercanas commented on src/components/FlagPortal/styles.js
> +const StyledContainer = styled.div`
Change StyledContainer to be a `ul` and remove the margin that the browser auto adds to this kind of element.

2024-08-28 15:30 UTC, wfercanas commented on src/components/FlagPortal/styles.js
> +  @media (max-width: 400px) {
Refactor this media query. The purpose of this container is to fix the position from where we'll start rendering flags, so, it would look something like this:

```css
right: 64px
bottom: 32px

@media screen and (max-width: 528px) {
  bottom: 16px;
  right: 32px
}
```

Note: 
1. **528px** is an important breakpoint here because the flag normally has 400px in width + 64px right + 64 px left = 528px.
2. This means that we should work with that breakpoint to shift between variants of the flag.

2024-08-28 15:30 UTC, wfercanas commented on src/components/Flag/styles.js
> +  width: 100%;
Don't work with max-widths and max-heights, go straight to the normal dimensions of the component and then adjust with the media query. Something like this:

```css
width: 400px;
height: 82px;

@media and screen (max-width: 528px) {
  height: 62px; /* Check figma to confirm */
  width: calc(100vw - 64px) /* This makes the flag adjust to the available space without using the margins */
}

```

2024-08-28 15:30 UTC, wfercanas commented on src/components/FlagPortal/styles.js
Refactor to:
1. Remove all flex properties from StyledContainer. Use a Stack in the return of FlagPortal.
2. The z-index is not necessary for now. We're inserting the portal as the last DOM element in the body and display fixed. That should be enough for now.
3. The property of width: 100% is unnecessary.
4. The

2024-09-03 20:16 UTC, cmarin001 commented on src/components/Flag/index.tsx
> +        <StyledCloseIconContainer>
solved

2024-09-03 20:18 UTC, cmarin001 commented on src/components/Flag/index.tsx
> +        <StyledCountdownBarContainer>
solved

2024-09-03 20:26 UTC, cmarin001 commented on src/components/FlagPortal/FlagPortal.stories.tsx
> +      <FlagPortal />
solved

2024-09-03 20:32 UTC, cmarin001 commented on src/components/Flag/styles.js
>      0px 1px 3px 1px rgba(0, 0, 0, 0.15);
solved

2024-09-03 20:35 UTC, cmarin001 commented on src/components/Flag/styles.js
>  const StyledFlag = styled.div`
solved

2024-09-03 20:36 UTC, cmarin001 commented on src/components/FlagPortal/styles.js
> +const StyledContainer = styled.div`
solved

2024-09-03 21:13 UTC, cmarin001 commented on src/components/FlagPortal/styles.js
solved

2024-09-03 21:21 UTC, cmarin001 commented on src/components/FlagPortal/styles.js
> +  @media (max-width: 400px) {
solved

2024-09-03 21:21 UTC, cmarin001 commented on src/components/Flag/styles.js
> +  width: 100%;
solved

2024-09-04 17:24 UTC, wfercanas approved these changes

2024-09-04 17:31 UTC, merged